version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 4001:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
  
      
  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database", "${JOB_SCHEDULER_APP_DB_DSN}", "up"]
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:

